export const MOCK_MATCHES = [
  {
    id: "m-1",
    counterpartName: "Green Valley Greenhouse",
    role: "consumer",
    score: 92,
    distanceKm: 4.2,
    scheduleOverlap: "High",
    temperatureFit: "Strong",
    summary: "Stable daytime thermal demand with close pipe distance.",
    location: "West industrial corridor",
    contact: "ops@greenvalley.example",
    explanation: [
      "Strong process temperature overlap between 82 C supply and 71 C demand.",
      "Daily operating windows overlap for 10 hours on weekdays.",
      "Pipeline routing estimate stays under the target feasibility threshold.",
    ],
    coordinates: { lat: 51.502, lng: -0.11 },
  },
  {
    id: "m-2",
    counterpartName: "North District Heating Loop",
    role: "consumer",
    score: 84,
    distanceKm: 7.8,
    scheduleOverlap: "Medium",
    temperatureFit: "Strong",
    summary: "Excellent winter compatibility with moderate routing distance.",
    location: "North service zone",
    contact: "network@northloop.example",
    explanation: [
      "Strong heat demand profile through colder months.",
      "Requires a storage buffer to smooth production peaks.",
      "Good fit for phased deployment after pilot validation.",
    ],
    coordinates: { lat: 51.527, lng: -0.088 },
  },
  {
    id: "m-3",
    counterpartName: "ColdStore One Logistics",
    role: "consumer",
    score: 76,
    distanceKm: 11.3,
    scheduleOverlap: "Medium",
    temperatureFit: "Moderate",
    summary: "Potential fit with evening demand concentration.",
    location: "Harbor cold chain district",
    contact: "facilities@coldstore.example",
    explanation: [
      "Temperature lift may require supplemental heat pump support.",
      "Distance is workable but not ideal for a first deployment.",
      "Demand peaks in the evening, so schedule coordination matters.",
    ],
    coordinates: { lat: 51.489, lng: -0.072 },
  },
];
